= jandex-gradle-plugin
:linkattrs:
:project-owner:   kordamp
:project-repo:    maven
:project-name:    jandex-gradle-plugin
:project-group:   org.kordamp.gradle
:project-version: 0.8.0

image:https://github.com/{project-owner}/{project-name}/workflows/Build/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]
image:https://img.shields.io/badge/donations-Patreon-orange.svg[link="https://www.patreon.com/user?u=6609318"]

---

Runs `link:https://github.com/wildfly/jandex[jandex]` on a Gradle project.

== Usage

Option #1
[source,groovy]
[subs="attributes"]
----
buildscript {
    repositories {
        jcenter()
        gradlePluginPortal()
    }
    dependencies {
        classpath '{project-group}:{project-name}:{project-version}'
    }
}
apply plugin: '{project-group}.jandex'
----

Option #2
[source,groovy]
[subs="attributes"]
----
plugins {
    id '{project-group}.jandex' version '{project-version}'
}
----

This will add a `jandex` task to your build, which will analyze the `main` sourceSets by default, the generated index
will be placed in `${project.tasks.processResources.destinationDir}/META-INF/jandex.idx`.

== Configuration
=== Plugin configuration

The following properties can be specified in the `jandex` task configuration

[options="header"]
|===
| Name                  | Option                          | Property                        | Type     | Default Value
| processDefaultFileSet | jandex-process-default-file-set | jandex.process.default.file.set | boolean  | true
| indexName             | jandex-index-name               | jandex.index.name               | String   | jandex.idx
| destination           |                                 |                                 | File     | build/resources/main/META-INF/jandex.idx
| fileSets              |                                 |                                 | FileTree | sourceSets.main.output
|===

Task properties may be defined on the command line using their option name, or their property name, such as

[source]
----
$ gradle jandex --jandex-index-name foo.idx
$ gradle jandex -Pjandex.index.name=foo.idx
$ gradle jandex -Djandex.index.name=foo.idx
$ set JANDEX_INDEX_NAME=foo.idx
$ gradle jandex
----
