= jandex-gradle-plugin
:linkattrs:
:project-owner:   kordamp
:project-repo:    maven
:project-name:    jandex-gradle-plugin
:project-group:   org.kordamp.gradle
:project-version: 2.0.0
:jandex-version:  3.1.7
:plugin-id:       {project-group}.jandex

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

image:https://img.shields.io/github/actions/workflow/status/{project-owner}/{project-name}/early-access.yml?branch=master&logo=github&label=Build["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:https://img.shields.io/gradle-plugin-portal/v/{plugin-id}?logo=gradle["Gradle Plugin Portal", link="https://plugins.gradle.org/plugin/{plugin-id}"]

---

Runs `link:https://github.com/wildfly/jandex[jandex]` on a Gradle project.

== Usage

Option #1
[source,groovy]
[subs="attributes"]
----
buildscript {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    dependencies {
        classpath '{project-group}:{project-name}:{project-version}'
    }
}
apply plugin: '{project-group}.jandex'
----

Option #2
[source,groovy]
[subs="attributes"]
----
plugins {
    id '{project-group}.jandex' version '{project-version}'
}
----

This will add a `jandex` task to your build, which will analyze the `main` sourceSets by default, the generated index
will be placed in `${project.tasks.processResources.destinationDir}/META-INF/jandex.idx`.

NOTE: Requires Java 11+ and Gradle 8+.

== Configuration
=== Plugin configuration

The following properties can be specified in the `jandex` task configuration

[options="header"]
|===
| Name                  | Option                          | Property                        | Type                       | Default Value
| processDefaultFileSet | jandex-process-default-file-set | jandex.process.default.file.set | boolean                    | true
| includeInJar          | jandex-includein-jar            | jandex.include.in.jar           | boolean                    | true
| indexName             | jandex-index-name               | jandex.index.name               | String                     | jandex.idx
| indexVersion          | jandex-index-version            | jandex.index.version            | Integer                    |
| destination           |                                 |                                 | File                       | build/jandex/jandex.idx
| sources               |                                 |                                 | ConfigurableFileCollection | sourceSets.main.output.classesDirs
|===

NOTE: The generated index file will be copied to `build/resources/main/META-INF/jandex.idx during the invocation of the
`processResources` task if the `includeInJar` property is set to `true`.

Task properties may be defined on the command line using their option name, or their property name, such as

[source]
----
$ gradle jandex --jandex-index-name foo.idx
$ gradle jandex -Pjandex.index.name=foo.idx
$ gradle jandex -Djandex.index.name=foo.idx
$ set JANDEX_INDEX_NAME=foo.idx
$ gradle jandex
----

=== Jandex Version

This plugin relies on Jandex `{jandex-version}` to perform its job, however you may configure a different version if needed.
Simply add the desired version (for the maven coordinates `io.smallrye:jandex:<version>`) to the `jandex` extension as shown next

[source,groovy]
----
jandex {
    version = '3.0.0'
}
----

WARNING: This plugin supports Jandex 3 as a minimum since version `1.0.0`.

== Migration

Starting with version `0.9.0` the chosen Jandex dependency must be resolved using explicit repositories, in other words,
it is no longer part of the plugin's default classpath. Failure to declare a repository from which this dependency may be
resolved will result in a build failure.

